version: '3.1'

services: 
  guacamole:
    image: oznu/guacamole
    container_name: guacamole-kr1ps
    restart: always
    volumes:
      - ./config:/config
    ports:
      - 8086:8080
    network_mode: bridge
